export enum Page {
  Dashboard = "DASHBOARD",
  ThemeAssistant = "THEME_ASSISTANT",
  Budget = "BUDGET",
  Guests = "GUESTS",
  Vendors = "VENDORS",
  Tasks = "TASKS",
  Messages = "MESSAGES",
  Settings = "SETTINGS",
  GamePlanner = "GAME_PLANNER",
  Invitation = "INVITATION",
  GiftRegistry = "GIFT_REGISTRY",
  InvitationEditor = "INVITATION_EDITOR",
  InvitationPasswordGate = "INVITATION_PASSWORD_GATE",
  AIThankYouHelper = "AI_THANK_YOU_HELPER",
}
